# Configuración de Proyecto SonarCloud para AsistenciasUCO-DB
sonar.organization=algomuyseguro1234
sonar.projectKey=algomuyseguro1234_AsistenciasUCO-DB
sonar.projectName=AsistenciasUCO-DB
sonar.projectVersion=1.0

# Fuentes a analizar
sonar.sources=.
sonar.inclusions=schema/**/*.sql,*.ps1
sonar.exclusions=scratch/**,test/**,docs/**,schema/seed/**
sonar.coverage.exclusions=**/*.sql,*.ps1

# Codificación
sonar.sourceEncoding=UTF-8
